version: '3.4'

services:
  shopclient:
    image: shop-client
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
      - 9230:9229
    volumes:
      - ./src:/usr/src/app/src/:ro
      - ./public:/usr/src/app/public/:ro
